export const services = [
  {slug:'implantologie', name:'Implantologie', short:'Un nou început. Cu o bază solidă.', description:'Reconstruim funcția și estetica zâmbetului folosind planificare modernă și soluții adaptate fiecărui caz.', price:'2.100', image:'precision', doctor:0, hero:'Implantologia modernă începe cu un plan precis.', overview:'Înlocuirea unui dinte începe cu înțelegerea întregului zâmbet. Evaluarea clinică și investigațiile recomandate ajută medicul să aleagă o soluție potrivită.', benefits:['Planificare digitală în funcție de anatomia ta','Opțiuni discutate pe înțelesul tău','Continuitate până la lucrarea finală'], suitable:'Pentru persoane cu unul sau mai mulți dinți lipsă. Starea osului, sănătatea gingiilor și istoricul medical influențează eligibilitatea; aceasta se stabilește la consultație.', steps:['Consultație și investigații','Plan individual și estimarea costurilor','Intervenție și perioadă de vindecare','Lucrare protetică și controale'], faqs:[['Cât durează tratamentul?','Durata depinde de vindecare, de volumul osos și de etapele necesare. Medicul poate estima calendarul după evaluare.'],['Prețul include și coroana?','Tariful de pornire se referă la implant. Investigațiile, bontul, coroana și eventualele proceduri suplimentare se discută separat în plan.'],['Ce presupune îngrijirea ulterioară?','Igiena zilnică și controalele periodice sunt importante. Recomandările și frecvența vizitelor sunt adaptate fiecărei situații.']]},
  {slug:'estetica-dentara',name:'Estetică dentară',short:'Natural. În fiecare detaliu.',description:'Albire și restaurări atent planificate, în armonie cu trăsăturile tale și sănătatea dinților.',price:'650',image:'smile',doctor:1,hero:'Zâmbetul tău. În cea mai firească lumină.',overview:'Un zâmbet armonios păstrează ceea ce te face unic. Discutăm despre nuanță, formă și proporții, apoi alegem împreună opțiunile potrivite.',benefits:['Un rezultat estetic cu aspect natural','Alegerea nuanței și a formei împreună','Sănătatea dentară înaintea schimbărilor estetice'],suitable:'Pentru persoane care doresc să discute despre culoarea, forma sau mici imperfecțiuni ale dinților. Cariile și afecțiunile gingivale trebuie evaluate înaintea procedurilor estetice.',steps:['Discuție despre așteptări','Evaluare și fotografii de diagnostic','Alegerea soluției și a nuanței','Tratament și recomandări de îngrijire'],faqs:[['Albirea este potrivită pentru oricine?','Indicația se stabilește după consultație. Coroanele și obturațiile nu se albesc în același mod ca dinții naturali.'],['Poate apărea sensibilitate?','Unele persoane pot avea sensibilitate temporară. Medicul explică măsurile de confort și recomandările potrivite.'],['Cât se menține nuanța?','Efectul variază în funcție de obiceiuri, alimentație și igienă. Nu se poate promite o durată identică pentru fiecare persoană.']]},
  {slug:'ortodontie',name:'Ortodonție',short:'Mai mult decât dinți aliniați.',description:'Aparate dentare și un plan de tratament care urmărește echilibrul dintre funcție și estetică.',price:'2.900',suffix:' / arcadă',image:'smile',doctor:2,hero:'Un zâmbet în echilibru. Pas cu pas.',overview:'Ortodonția urmărește atât alinierea dinților, cât și relația dintre arcade. Un plan atent și vizitele regulate sunt parte din același parcurs.',benefits:['Opțiuni de aparat explicate clar','Monitorizare pe parcursul tratamentului','Plan de contenție după aliniere'],suitable:'Pentru copii, adolescenți și adulți cu nevoi de aliniere sau corectare a mușcăturii. Momentul începerii și tipul aparatului sunt stabilite în urma evaluării.',steps:['Consultație și documentare','Analiza mușcăturii și plan de tratament','Aplicarea aparatului și controale','Îndepărtarea aparatului și contenție'],faqs:[['Pot începe tratamentul ca adult?','Vârsta singură nu exclude tratamentul. Sănătatea dinților, gingiilor și osului se evaluează înainte de recomandare.'],['Cât de des sunt controalele?','Intervalul este stabilit de medic în funcție de aparat și de etapa tratamentului.'],['Prețul este pentru ambele arcade?','Tarifele pentru aparate sunt prezentate pe arcadă. Consultațiile, activările și contenția se clarifică în planul individual.']]},
  {slug:'endodontie',name:'Endodonție',short:'Precizie care păstrează.',description:'Tratamente de canal realizate cu atenție la detalii, cu ajutorul microscopului dentar.',price:'900',image:'precision',doctor:1,hero:'Grijă pentru dintele tău. Până la cel mai mic detaliu.',overview:'Tratamentul endodontic urmărește tratarea interiorului dintelui atunci când pulpa este afectată. Microscopul oferă medicului vizibilitate sporită în etapele delicate.',benefits:['Vizibilitate sporită la microscop','Evaluarea șanselor de păstrare a dintelui','Recomandare pentru restaurarea finală'],suitable:'Pentru dinți cu afectare pulpară sau pentru anumite retratamente. Diagnosticul și posibilitatea de restaurare a dintelui trebuie evaluate clinic și radiologic.',steps:['Diagnostic și evaluarea dintelui','Izolare și acces la canale','Curățare și obturare a canalelor','Restaurare și urmărire'],faqs:[['Câte ședințe sunt necesare?','Numărul ședințelor depinde de anatomie, infecție și complexitatea cazului. Medicul discută estimarea după diagnostic.'],['Tratamentul include coroana?','Restaurarea finală se stabilește separat, în funcție de cât țesut dentar a rămas și de solicitările dintelui.'],['Pot apărea simptome după tratament?','Poate exista disconfort temporar. Medicul oferă recomandări individuale și explică situațiile în care este necesară reevaluarea.']]},
  {slug:'stomatologie-generala',name:'Stomatologie generală',short:'Grija de zi cu zi contează.',description:'Consultații, prevenție și tratamentul cariilor, pentru o bază sănătoasă a zâmbetului.',price:'120',image:'clinic'},
  {slug:'protetica-dentara',name:'Protetică dentară',short:'Funcție și firesc.',description:'Coroane și lucrări protetice alese în funcție de nevoile funcționale și estetice.',price:'550',image:'precision'},
  {slug:'chirurgie',name:'Chirurgie dento-alveolară',short:'Fiecare etapă, explicată.',description:'Evaluare atentă, intervenții planificate și îndrumare pentru perioada de recuperare.',price:'190',image:'precision'},
  {slug:'parodontologie',name:'Parodontologie',short:'Sănătatea începe cu gingiile.',description:'Evaluarea și îngrijirea țesuturilor care susțin dinții, cu un plan personalizat.',price:null,image:'clinic'},
  {slug:'pedodontie',name:'Pedodonție',short:'Pași mici. Încredere mare.',description:'Vizite adaptate copiilor, cu răbdare, explicații simple și atenție pentru prevenție.',price:null,image:'clinic'},
  {slug:'radiologie',name:'Radiologie & CBCT',short:'Vedem mai mult. Planificăm mai bine.',description:'Investigații imagistice recomandate în funcție de nevoia clinică și diagnosticul urmărit.',price:'40',image:'precision'}
];
export const team = [
  {name:'Dr. Andrei Popescu',role:'Implantologie & chirurgie orală',specialty:'Planificare digitală · Reabilitare orală',bio:'În acest profil demonstrativ, Andrei pune accent pe explicarea opțiunilor și pe un parcurs de tratament ușor de urmărit. Interese: planificarea digitală și colaborarea interdisciplinară.',slug:'andrei-popescu'},
  {name:'Dr. Elena Marinescu',role:'Estetică dentară & protetică',specialty:'Estetică naturală · Restaurări dentare',bio:'Profilul demonstrativ al Elenei reflectă o abordare atentă la proporții, funcție și dorințele pacientului. Interese: restaurări cu aspect natural și păstrarea țesutului dentar.',slug:'elena-marinescu'},
  {name:'Dr. Radu Ionescu',role:'Ortodonție',specialty:'Echilibru funcțional · Aliniere dentară',bio:'În acest profil demonstrativ, Radu explică fiecare etapă a tratamentului și importanța continuității. Interese: relația dintre aliniere, mușcătură și stabilitatea rezultatului.',slug:'radu-ionescu'},
  {name:'Maria Dumitru',role:'Asistent medical',specialty:'Grijă · Organizare · Confort',bio:'Profil demonstrativ. Maria reprezintă grija pentru pregătirea fiecărei vizite și pentru confortul persoanei aflate în cabinet.',slug:'maria-dumitru'},
  {name:'Ioana Stan',role:'Asistent medical',specialty:'Sprijin · Comunicare · Atenție',bio:'Profil demonstrativ. Ioana reprezintă sprijinul oferit pe parcursul vizitei, prin comunicare calmă și atenție la detalii.',slug:'ioana-stan'}
];
export const prices = [
  ['Consultații',[['Consultație stomatologică','120 lei'],['Consultație ortodonție','160 lei'],['Consultație chirurgie','170 lei']]],
  ['Radiologie',[['Radiografie panoramică','100 lei'],['Radiografie retroalveolară','40 lei'],['CBCT segmentar','210 lei'],['CBCT bimaxilar','420 lei']]],
  ['Stomatologie generală',[['Obturație mică','210 lei'],['Obturație medie','240 lei'],['Obturație mare','270 lei'],['Obturație frontală','320 lei']]],
  ['Estetică',[['Albire profesională','650 lei'],['Albire premium','1.050 lei']]],
  ['Endodonție',[['Tratament endodontic la microscop monoradicular','900 lei'],['Tratament endodontic la microscop pluriradicular','950 lei']]],
  ['Implantologie',[['Implant dentar','de la 2.100 lei'],['Implant premium','de la 2.350 lei']]],
  ['Chirurgie',[['Extracție dentară','de la 190 lei'],['Extracție molar de minte','de la 370 lei']]],
  ['Protetică',[['Coroană metalo-ceramică','de la 550 lei'],['Coroană zirconiu','de la 1.050 lei'],['Coroană zirconiu pe implant','2.550 lei']]],
  ['Ortodonție',[['Aparat fix metalic','2.900 lei / arcadă'],['Aparat ceramic','3.350 lei / arcadă'],['Aparat safir','4.100 lei / arcadă']]]
];
export const cases = [
 {id:'01',title:'Luminozitate, păstrând naturalețea',category:'estetica',tags:'Estetică dentară · Albire dentară',duration:'2 săptămâni',problem:'Scenariu ilustrativ: colorație dentară generalizată și dorința unei nuanțe mai luminoase.',approach:'Consultație, evaluarea sănătății orale și albire dentară profesională supravegheată.',result:'Obiectivul scenariului: uniformizarea nuanței, păstrând aspectul natural al dinților.'},
 {id:'02',title:'O nuanță mai uniformă',category:'estetica',tags:'Estetică dentară',duration:'2 săptămâni',problem:'Scenariu ilustrativ: variații de culoare care afectează armonia zâmbetului.',approach:'Evaluarea eligibilității și alegerea protocolului de albire dentară potrivit.',result:'Obiectivul scenariului: o nuanță mai uniformă, cu un rezultat estetic firesc.'},
 {id:'03',title:'Un zâmbet în echilibru',category:'ortodontie',tags:'Ortodonție',duration:'18 luni',problem:'Scenariu ilustrativ: aliniere neregulată și dezechilibru între arcade.',approach:'Documentare, aparat dentar, monitorizare și plan de contenție.',result:'Obiectivul scenariului: îmbunătățirea alinierii și a relației dintre arcade.'}
];
