export const services = [
  {slug:'implantologie', name:'Dental implants', short:'A new beginning. Built on a solid foundation.', description:'We restore oral function and smile aesthetics through modern planning and solutions tailored to each case.', price:'2,100', image:'precision', doctor:0, hero:'Modern implant dentistry begins with precise planning.', overview:'Replacing a tooth begins with understanding the whole smile. A clinical examination and the recommended diagnostic tests help the dentist select an appropriate solution.', benefits:['Digital planning based on your anatomy','Options explained in clear, accessible language','Continuity of care through to the final restoration'], suitable:'For people missing one or more teeth. Bone volume, gum health and medical history influence suitability, which is established during the consultation.', steps:['Consultation and diagnostic tests','Individual treatment plan and cost estimate','Implant placement and healing period','Final prosthetic restoration and follow-up'], faqs:[['How long does treatment take?','The timeline depends on healing, available bone volume and the procedures required. Your dentist can provide an estimate after the assessment.'],['Does the price include the crown?','The starting price covers the dental implant. Diagnostic tests, the abutment, crown and any additional procedures are itemised separately in the treatment plan.'],['What does aftercare involve?','Daily oral hygiene and regular reviews are important. Recommendations and recall intervals are tailored to each situation.']]},
  {slug:'estetica-dentara',name:'Cosmetic dentistry',short:'Natural. In every detail.',description:'Whitening and restorations planned with care to complement your features while protecting dental health.',price:'650',image:'smile',doctor:1,hero:'Your smile. In its most natural light.',overview:'A harmonious smile preserves what makes you unique. We discuss shade, shape and proportions, then choose the appropriate options together.',benefits:['A natural-looking aesthetic result','Shade and shape selected together','Oral health addressed before cosmetic changes'],suitable:'For people who would like to discuss tooth colour, shape or minor imperfections. Tooth decay and gum disease must be assessed before cosmetic procedures.',steps:['Discussion of your expectations','Clinical assessment and diagnostic photographs','Selecting the treatment and shade','Treatment and aftercare advice'],faqs:[['Is tooth whitening suitable for everyone?','Suitability is established after a consultation. Crowns and fillings do not whiten in the same way as natural teeth.'],['Can sensitivity occur?','Some people may experience temporary sensitivity. The dentist will explain comfort measures and suitable recommendations.'],['How long will the shade last?','The effect varies with habits, diet and oral hygiene. The same duration cannot be guaranteed for every person.']]},
  {slug:'ortodontie',name:'Orthodontics',short:'More than straight teeth.',description:'Braces and a treatment plan designed to balance oral function and aesthetics.',price:'2,900',suffix:' / arch',image:'smile',doctor:2,hero:'A balanced smile. Step by step.',overview:'Orthodontic treatment addresses both tooth alignment and the relationship between the dental arches. Careful planning and regular review appointments are part of the same journey.',benefits:['Orthodontic appliance options explained clearly','Regular monitoring throughout treatment','A retention plan after alignment'],suitable:'For children, teenagers and adults who need tooth alignment or bite correction. The right time to begin and the type of appliance are established after an assessment.',steps:['Consultation and diagnostic records','Bite analysis and treatment planning','Fitting the appliance and regular reviews','Appliance removal and retention'],faqs:[['Can I start treatment as an adult?','Age alone does not rule out treatment. The health of your teeth, gums and supporting bone is assessed before a recommendation is made.'],['How often are review appointments needed?','The interval is set by the orthodontist according to the appliance and stage of treatment.'],['Is the price for both arches?','Appliance fees are shown per arch. Consultation, adjustment and retention fees are detailed in the individual treatment plan.']]},
  {slug:'endodontie',name:'Endodontics',short:'Precision that preserves.',description:'Root canal treatment performed with close attention to detail using a dental operating microscope.',price:'900',image:'precision',doctor:1,hero:'Care for your tooth. Down to the smallest detail.',overview:'Endodontic treatment addresses the inside of a tooth when the dental pulp is affected. The operating microscope provides enhanced visibility during delicate stages of treatment.',benefits:['Enhanced visibility under magnification','Assessment of whether the tooth can be preserved','Advice on the definitive restoration'],suitable:'For teeth with pulpal disease and for selected retreatment cases. Diagnosis and the restorability of the tooth must be assessed clinically and radiographically.',steps:['Diagnosis and assessment of the tooth','Isolation and access to the root canal system','Cleaning, shaping and obturation of the canals','Definitive restoration and follow-up'],faqs:[['How many appointments are required?','The number of appointments depends on root canal anatomy, infection and case complexity. The dentist will discuss an estimate after diagnosis.'],['Does treatment include the crown?','The definitive restoration is planned separately based on the remaining tooth structure and the functional load on the tooth.'],['Can symptoms occur after treatment?','Temporary discomfort may occur. The dentist will provide individual advice and explain when reassessment is needed.']]},
  {slug:'stomatologie-generala',name:'General dentistry',short:'Everyday care matters.',description:'Examinations, prevention and treatment of tooth decay for a healthy foundation.',price:'120',image:'clinic'},
  {slug:'protetica-dentara',name:'Prosthodontics',short:'Function, restored naturally.',description:'Crowns and prosthetic restorations selected according to functional and aesthetic needs.',price:'550',image:'precision'},
  {slug:'chirurgie',name:'Oral surgery',short:'Every stage, clearly explained.',description:'Careful assessment, planned procedures and guidance throughout recovery.',price:'190',image:'precision'},
  {slug:'parodontologie',name:'Periodontics',short:'Health begins with your gums.',description:'Assessment and care of the tissues supporting the teeth, with an individual treatment plan.',price:null,image:'clinic'},
  {slug:'pedodontie',name:'Paediatric dentistry',short:'Small steps. Lasting confidence.',description:'Child-centred visits with patience, simple explanations and a focus on prevention.',price:null,image:'clinic'},
  {slug:'radiologie',name:'Dental radiology & CBCT',short:'See more. Plan with confidence.',description:'Diagnostic imaging recommended according to clinical need and the diagnosis being investigated.',price:'40',image:'precision'}
];

export const team = [
  {name:'Dr Andrei Popescu',role:'Implant dentistry & oral surgery',specialty:'Digital planning · Oral rehabilitation',bio:'In this fictional profile, Andrei focuses on explaining the available options and creating an easy-to-follow treatment journey. Interests: digital planning and interdisciplinary care.',slug:'andrei-popescu'},
  {name:'Dr Elena Marinescu',role:'Cosmetic dentistry & prosthodontics',specialty:'Natural aesthetics · Restorative dentistry',bio:'Elena’s fictional profile reflects a careful approach to proportions, function and the patient’s preferences. Interests: natural-looking restorations and preservation of tooth structure.',slug:'elena-marinescu'},
  {name:'Dr Radu Ionescu',role:'Orthodontics',specialty:'Functional balance · Tooth alignment',bio:'In this fictional profile, Radu explains every stage of treatment and the importance of continuity. Interests: the relationship between alignment, the bite and long-term stability.',slug:'radu-ionescu'},
  {name:'Maria Dumitru',role:'Dental nurse',specialty:'Care · Organisation · Comfort',bio:'Fictional profile. Maria represents the care involved in preparing each visit and supporting the patient’s comfort in the treatment room.',slug:'maria-dumitru'},
  {name:'Ioana Stan',role:'Dental nurse',specialty:'Support · Communication · Attention',bio:'Fictional profile. Ioana represents calm communication, attention to detail and support throughout each visit.',slug:'ioana-stan'}
];

export const prices = [
  ['Consultations',[['Dental consultation','120 RON'],['Orthodontic consultation','160 RON'],['Oral surgery consultation','170 RON']]],
  ['Dental radiology',[['Panoramic radiograph','100 RON'],['Periapical radiograph','40 RON'],['Sectional CBCT scan','210 RON'],['Dual-arch CBCT scan','420 RON']]],
  ['General dentistry',[['Small filling','210 RON'],['Medium filling','240 RON'],['Large filling','270 RON'],['Anterior composite filling','320 RON']]],
  ['Cosmetic dentistry',[['Professional tooth whitening','650 RON'],['Premium tooth whitening','1,050 RON']]],
  ['Endodontics',[['Microscope-assisted root canal treatment — single-rooted tooth','900 RON'],['Microscope-assisted root canal treatment — multi-rooted tooth','950 RON']]],
  ['Dental implants',[['Dental implant','from 2,100 RON'],['Premium dental implant','from 2,350 RON']]],
  ['Oral surgery',[['Tooth extraction','from 190 RON'],['Wisdom tooth extraction','from 370 RON']]],
  ['Prosthodontics',[['Porcelain-fused-to-metal crown','from 550 RON'],['Zirconia crown','from 1,050 RON'],['Implant-supported zirconia crown','2,550 RON']]],
  ['Orthodontics',[['Fixed metal braces','2,900 RON / arch'],['Ceramic braces','3,350 RON / arch'],['Sapphire braces','4,100 RON / arch']]]
];

export const cases = [
  {id:'01',title:'Rebuilding a front tooth',category:'estetica',tags:'Cosmetic dentistry · Direct restoration',duration:'1 appointment',problem:'Illustrative scenario: loss of tooth structure affecting a front tooth, visible on the left side of the image.',approach:'A direct composite restoration shaped to rebuild the tooth\'s form and edge and blend naturally with the surrounding smile.',result:'Scenario objective: restore the affected tooth locally while preserving the smile\'s natural character.'},
  {id:'02',title:'A more even tooth shade',category:'estetica',tags:'Cosmetic dentistry',duration:'2 weeks',problem:'Illustrative scenario: variations in tooth colour affecting smile harmony.',approach:'Assessment of suitability and selection of an appropriate tooth-whitening protocol.',result:'Scenario objective: a more even shade with a natural-looking aesthetic result.'},
  {id:'03',title:'A balanced smile',category:'ortodontie',tags:'Orthodontics',duration:'18 months',problem:'Illustrative scenario: irregular alignment and an imbalance between the dental arches.',approach:'Diagnostic records, orthodontic appliance, monitoring and a retention plan.',result:'Scenario objective: improve alignment and the relationship between the dental arches.'}
];
